### ISSUE TITLE
end of file reached (EOFError) While running the script

### ISSUE THREAD

**Issue by VeeanB** [watir/ww_note#3]
Please can any one help me to resolve this issue

**Comment by kieuhua** [comment]
Me too. All I do is
browser = Watir::Browser.new :chrome
browser.goto("http//watir.com"

And a chrome browser pop up with Not Secure | data:, 
with this error message =end of file reached (EOFError)

**Comment by p0deje** [comment]
This is not a repository anybody looks at. See https://github.com/watir/watir.

**Comment by kieuhua** [comment]
Thanks, I think I solved the problem. It seems that I can only go to
localhost

browser = Watir::Browser.new :chrome, :switches => %w[--disable-gpu
--headless ]  # this workbrowser.goto("http://localhost:3000/")

print browser.title
#expect(browser.title).to eq("Watir")
expect(browser.title.include?("Ruby on Rails")).to be_truthy
#expect(browser.title.include?("Ruby")).to be_falsey
expect(browser.title).not_to include("Selenium")

**Comment by kieuhua** [comment]
sorry, the message return premature
It seems that I can only go to localhost, perhaps because my verizon router
from home.
Using --headless, and disable-gnu, I can

browser = Watir::Browser.new :chrome, :switches => %w[--disable-gpu
--headless]
browser.goto("http://localhost:3000")
expect(browser.title.include?)("Ruby").to be thruthy
print browser.title

All above code work, but if I go to out to outside site it doesn't work
browser.goto("http://mit.edu")
print browser.title
# => no erro, but no title output neither.

Thank you very much for your responses.

Kieu
